Repository tphakala/birdnet-go, pull requests merged in 2025-10, with the labels that each got.

#1341 fix(processor): remove detection window scaling from minDetections calculation
  internal/analysis/processor/mindetections_test.go
  internal/analysis/processor/processor.go
Labels: bug

#1336 feat: push notification infrastructure
  cmd/notify/notify.go
  cmd/root.go
  go.mod
  go.sum
  internal/conf/config.go
  internal/conf/config.yaml
  internal/conf/defaults.go
  internal/conf/validate.go
  internal/notification/push_dispatcher.go
  internal/notification/push_dispatcher_test.go
  internal/notification/push_provider.go
  internal/notification/push_script.go
  internal/notification/push_shoutrrr.go
  internal/telemetry/system_init_manager.go
  scripts/push-provider-test.sh
Labels: enhancement, pkg:telemetry

#1348 feat(notification): Add metrics, circuit breakers, and health checks
  internal/conf/config.go
  internal/conf/config.yaml
  internal/conf/defaults.go
  internal/notification/DOS_PROTECTION.md
  internal/notification/METRICS_AND_HEALTH_CHECKS.md
  internal/notification/circuit_breaker.go
  internal/notification/circuit_breaker_test.go
  internal/notification/health_check.go
  internal/notification/push_dispatcher.go
  internal/notification/push_dispatcher_test.go
  internal/notification/push_script.go
  internal/notification/push_shoutrrr.go
  internal/notification/rate_limiter.go
  internal/observability/metrics.go
  internal/observability/metrics/notification.go
Labels: enhancement, pkg:telemetry

#1350 fix(linter): resolve all golangci-lint errors for zero-error policy
  cmd/notify/notify.go
  internal/conf/validate.go
  internal/notification/push_dispatcher.go
  internal/notification/push_dispatcher_test.go
Labels: bug

#1352 feat(notification): Add webhook provider with reusable HTTP client
  internal/conf/config.go
  internal/conf/config.yaml
  internal/conf/validate.go
  internal/httpclient/client.go
  internal/httpclient/client_test.go
  internal/notification/WEBHOOK.md
  internal/notification/push_dispatcher.go
  internal/notification/push_webhook.go
  internal/notification/push_webhook_test.go
  internal/secrets/secrets.go
  internal/secrets/secrets_test.go
Labels: enhancement, pkg:telemetry

#1354 feat(notification): Migrate to maintained shoutrrr fork
  go.mod
  go.sum
  internal/notification/push_shoutrrr.go
Labels: dependencies
